### ISSUE TITLE
Get Existing Orders By Pair and Fill An Order

### ISSUE THREAD

**Issue by pointtoken** [dexDev/dexAPI#13]
Hi - Is there a way to get existing orders by pair and then to fill an order? Seem to be missing from the API..

**Comment by libreoscar** [comment]
Do you mean get depth?
https://github.com/dexDev/dexAPI#getpairdepth

**Comment by pointtoken** [comment]
Unfortunately, the getPairDepth api doesn't provide the actual order ids. And, even if it did, there is no api for actually filling one of those orders.

**Comment by libreoscar** [comment]
No, one cannot specify an order to fill. Neither there is an API, nor it is supported. DEx.top is not an OTC platform.
